### ISSUE TITLE
Support basic http authentication

### ISSUE THREAD

**Issue by faern** [mullvad/jsonrpc-client-rs#3]

**Comment by thomaseizinger** [comment]
As far as I can tell is setting custom headers already supported by the current version of the master branch. This should setting hyper-authorization headers.
When do you plan on releasing the next version? Anything that is missing for that?

**Comment by faern** [comment]
Latest master indeed support custom headers. Which would close this card. It's more or less ready for release. We just want to use and test it a bit more.

But I'm closing this card since it's fixed on master.
