### ISSUE TITLE
Example Server-Client code

### ISSUE THREAD

**Issue by MathieuDutSik** [mullvad/jsonrpc-client-rs#55]
In the issue "JSON-RPC client and server on the same TCP socket" the question was posed whether you could have code that works both as server and client for json. The answer for the jsonrpc library appears to be no that this is not possible.
The answer to the question indicate that one should look at the *jsonrpc-client-rs* for such an example (if it is possible at all). However, I cannot find any such example.
Is it at all possible to have a jsonrpc server that does a server job of processing requests but also sends request to other servers? Thank you very much for clarifying this.

**Comment by pronebird** [comment]
Hi, could you please share the link to the issue you refer to, namely "JSON-RPC client and server on the same TCP socket"?

**Comment by MathieuDutSik** [comment]
Thank you very much for reply. I need to continue working on the issue.

But I have a definite item that I think deserves mention in the existing small manual.
The thing is that there is no "https://api.fizzbuzzexample.org/rpc/". If one implements
it locally, e.g. on "http://127.0.0.1:8906" then the corresponding server code is

> extern crate jsonrpc_core;
> extern crate jsonrpc_http_server;
> #[macro_use]
> extern crate serde_derive;
> extern crate serde;
> extern crate serde_json;
> 
> use std::net::{IpAddr, Ipv4Addr, SocketAddr};
> use jsonrpc_core::*;
> use jsonrpc_http_server::{ServerBuilder};
> 
> #[derive(Serialize, Deserialize)]
> struct TypeEch {
>     eval: i32,
> }
> 
> fn main() {
>     let fizz_buzz = |eval: i32| -> String{
>         if eval == 3 { return "fizz".to_string();}
>         if eval == 4 { return "4".to_string(); }
>         if eval == 5 { return "buzz".to_string(); }
>         return "unset".to_string();
>     };
>     //                                                                                                             
>     let mut io = IoHandler::new();
>     io.add_method("fizz_buzz", move |params: Params| {
>         match params.parse::<TypeEch>() {
>             Ok(val) => Ok(Value::String(fizz_buzz(val.eval))),
>             Err(e) => {
>                 println!("Error during parsing {:?}", e);
>                 Ok(Value::String("Something went wrong".into()))
>             },
>         }
>     });
>     //                                                                                                             
>     let my_hostname = IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1));
>     let socket = SocketAddr::new(my_hostname, 8906);
>     //                                                                                                             
>     let server = ServerBuilder::new(io)
>         .start_http(&socket)
>         .expect("Server must start with no issues");
>     server.wait()
> }

That is one surprise for me is that the type "i32" from the server is not read directly
in the json server and that one needs to encapsulate it in a specific container type.

**Comment by pronebird** [comment]
`http://api.fizzbuzzexample.org/rpc/` is apparently an example. Just use any existing RPC that you wish to interact with.

I am pretty sure you can encode `i32` without wrapping it into `enum`. What error and input do you see? Make sure to match the types between client and server too. In our example we use `u64` which may be serialised differently from `i32`.

**Comment by MathieuDutSik** [comment]
Hi @pronebird . Yes, I well realized that *http://api.fizzbuzzexample.org/rpc/* is not existent. That being said it is well known that when working with jsonrpc, a big chunk of the bugs happen when one side has different understanding of the data from the other side.

In that specific case, I implemented as *u64* as you recommended. And I can confirm the problem. I got an error of the form "Error { code: InvalidParams, message: "Invalid params: invalid type: sequence, expected u64.", data: None }". Following code was used

> extern crate jsonrpc_core;
> extern crate jsonrpc_http_server;
> use std::net::{IpAddr, Ipv4Addr, SocketAddr};
> use jsonrpc_core::*;
> use jsonrpc_http_server::{ServerBuilder};
> fn main() {
>     let fizz_buzz = |eval: u64| -> String{
>         if eval == 3 { return "fizz".to_string();}
>         if eval == 4 { return "4".to_string(); }
>         if eval == 5 { return "buzz".to_string(); }
>         return "unset".to_string();
>     };
>     let mut io = IoHandler::new();
>     io.add_method("fizz_buzz", move |params: Params| {
>         match params.parse::<u64>() {
>             Ok(val) => Ok(Value::String(fizz_buzz(val))),
>             Err(e) => {
>                 println!("Error during parsing {:?}", e);
>                 Ok(Value::String("Something went wrong".into()))
>             },
>         }
>     });
>     let my_hostname = IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1));
>     let socket = SocketAddr::new(my_hostname, 8906);
>     let server = ServerBuilder::new(io)
>         .start_http(&socket)
>         .expect("Server must start with no issues");
>     server.wait()
> }

That is jsonrpc_client has encoded the entry as
> '{"jsonrpc": "2.0",  "method": "fizz_buzz",  "params": [4], "id" : 1 }'
and it fails the identification by the server. However, the
> '{"jsonrpc": "2.0",  "method": "fizz_buzz",  "params": 4, "id" : 1 }'

fails earlier with error
> {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":1}

The encapsulating of the value in a struct allows the parsing to be done correctly.
I think that this unfortunate situation may be unsolvable because there are too many
codes depending on this. Also, it is unclear to me if the client needs to be corrected
or the server.

But in the end, what I think is that it would be helpful to have pairs of codes client/server.
This would maybe help some users.

**Comment by pronebird** [comment]
As per JSON RPC 2.0 spec, `params` can either be passed by position (array) or by name (dictionary).

We do implement passing params by position as far as I know, so the library correctly throws the "Invalid request" when you attempt to feed it with a number.

Please get familiar with the spec, section 4.2 in particular:
https://www.jsonrpc.org/specification

I am closing this issue since I believe it's resolved.
