### ISSUE TITLE
Named parameters?

### ISSUE THREAD

**Issue by sebmalek** [mullvad/jsonrpc-client-rs#64]
So far I've only been able to make a request where parameters are simply a list of argument values, i.e.:

```
jsonrpc_client!(pub struct MoneroClient {
    pub fn create_address(&mut self, account_index: u32) -> RpcRequest<String>;
});
...
let result = client.create_address(0).call().unwrap();
```

resulting in:

```
{"jsonrpc":"2.0","method":"create_address","params":[0],"id":1}
```

How can I make a request with named parameters? For example:
`{"jsonrpc":"2.0","id":"0","method":"create_address","params":{"account_index":0}}`

Spec: https://docs.actian.com/openroad/6.2/index.html#page/ServerRef/JSON-RPC_Request_Named_Parameters.htm

Thanks!

**Comment by sebmalek** [comment]
@faern Any chance you could help me with this? Thanks :pray:

**Comment by faern** [comment]
This crate does not support named parameters as far as I can remember.

This crate is also *highly* unmaintained and outdated. The dependencies it's relying on are ancient by now (`tokio-core 0.1`, I'm looking at you :eyes:)

**Comment by faern** [comment]
I have not used JSON-RPC for years now. So I don't know what's the best in the ecosystem. I hope you'll find something up to date that works well for you :)
